### ISSUE TITLE
你好，在使用中发现一个问题

### ISSUE THREAD

**Issue by ohuangbino** [laravel-admin-extensions/cropper#1]
作者您好，我在使用中发现一个问题，为什么保存图片的时候不默认使用laravel的本地磁盘呢？现在的保存路径默认为pubilc目录下的uploads，但是项目很多地方用到的都是laravel本地磁盘路径的，所以这对项目路径有冲突啊，建议把 public_path() 方法改为 storage_path() 方法 或者在 admin.php 里面增加 config => ['路径配置']...

**Comment by EVA09** [comment]
因为 laravel-admin 默认要建立一个 新的filesystem配置
 'admin' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'url' => env('APP_URL').'/uploads',
            'visibility' => 'public',
        ],
其实我是在这个配置下沿用了路径。 当然你可以自己修改源码改到你喜欢的路径。 也许有时间的话我会开放一下配置接口。 或者你完全可以自己下载源码修改 emm

**Comment by zzDylan** [comment]
确实应该加个配置路径的接口，读取filesystem.admin.root配置，直接写死在代码里有点不太好，建议作者抽空加个配置，嘻嘻

**Comment by EVA09** [comment]
> 对鸭,我也遇到了这个问题,修改源码过于麻烦,建议可以像laravel-admin一样增加一个 move($path) 方法, 可以让用户比较方便地修改保存路径
额 我全量继承了 原有的image方法  所以 image方法使用的一切，crop也一样能使用。emm 包括这个move。。。

**Comment by 77zealous** [comment]
> 额 我全量继承了 原有的image方法 所以 image方法使用的一切，crop也一样能使用。emm 包括这个move。。。

支持 期待1.0.1!!!
