### ISSUE TITLE
再次编辑后存入数据库的字段中包含地址前缀

### ISSUE THREAD

**Issue by ShareManT** [laravel-admin-extensions/cropper#12]
首先，感谢作者将方便的cropper集成laravel-admin

问题描述：
比如 第一次添加内容 使用了cropper，存入数据库地址为 image/1
.jpg
再次编辑的时候 直接保存，会将该字段覆盖为 http(s)://xxx.com/image1.jpg

**Comment by EVA09** [comment]
1.0.2版本修复了该问题，但是只是打补丁式修补，可能会因为文件名等问题冲突，建议使用
composer require laravel-admin-ext/cropper:1.0.0
先还原到1.0.0版本，但是会失去文件重命名功能。之后的版本会彻底修复该bug
