### ISSUE TITLE
preg_match(): Unknown modifier 'a'

### ISSUE THREAD

**Issue by 77zealous** [laravel-admin-extensions/cropper#13]
更新1.0.2之后,若图片不修改更新其他字段然后保存提示 `preg_match(): Unknown modifier 'a'`

![Snipaste_2019-04-03_11-57-15.png](https://i.loli.net/2019/04/03/5ca42f395bd1a.png)

**Comment by EVA09** [comment]
你配置的上传路径是什么？

**Comment by 77zealous** [comment]
![UTOOLS1554264099844.png](https://i.loli.net/2019/04/03/5ca4302442410.png)

**Comment by EVA09** [comment]
尝试添加 $directory = str_replace('/',"\/",$directory); 在报错的位置试试

**Comment by 77zealous** [comment]
works for me!
Thanks!
