### ISSUE TITLE
可否兼容laravel-admin 1.5版本

### ISSUE THREAD

**Issue by kaiqiangdaniao** [laravel-admin-extensions/cropper#15]
可否兼容laravel-admin 1.5版本

![image](https://user-images.githubusercontent.com/9409758/56468606-4beded00-6461-11e9-9b1f-8bf016681978.png)

**Comment by EVA09** [comment]
这个没办法。 我自己手上是有1.5版本 我自己做好的。但是在1.5版本上面没有完整的插件开发机制。。。我顶多能告诉你怎么在1.5上用。 不能做成包
