### ISSUE TITLE
图片设置为required()时不传递图片JS报错无法正常提示

### ISSUE THREAD

**Issue by 38757974** [laravel-admin-extensions/cropper#17]
$form->cropper('thumb','图片')->required();
当这样设置后，前端没有选中图片就点击提交，页面没有任何翻译，JS报错；
An invalid form control with name='' is not focusable.

**Comment by songlen** [comment]
我也遇到这个情况了，不过，好像不是required的问题，我是偶尔出现了这个情况，required() 一直都有，前面没问题，后来报这个错了

**Comment by EVA09** [comment]
此问题修复了 这是因为  Chromium 的更新，早期html给不可见的input设置 require 属性是不会抱错的，但是近期更新之后，如果再给不可见的input设置require就会爆出这个提示了。 现在我给input设置为了透明这个问题算是解决了
