### ISSUE TITLE
vue 支持吗

### ISSUE THREAD

**Issue by rockmelodies** [laravel-admin-extensions/cropper#18]
请问，vue 支持吗

**Comment by EVA09** [comment]
你是问cropper 插件本身吗？ &nbsp;这个插件是独立的，你可以去搜索一下使用到你自己的项目里面



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rockymelody"<notifications@github.com&gt;; 
发送时间: 2019年11月3日(星期天) 上午10:38
收件人: "laravel-admin-extensions/cropper"<cropper@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [laravel-admin-extensions/cropper] vue 支持吗 (#18)




请问，vue 支持吗
 
&mdash;
