### ISSUE TITLE
更新时value值是绝对路径

### ISSUE THREAD

**Issue by weiwait** [laravel-admin-extensions/cropper#19]
在更新是把域名保存到数据库了
![TIM图片20191115102159](https://user-images.githubusercontent.com/17488095/68911994-c7aede80-0791-11ea-90de-1b8e90173426.png)

**Comment by weiwait** [comment]
![1573796373(1)](https://user-images.githubusercontent.com/17488095/68919528-6c8ae500-07ad-11ea-9d41-21e3a9057e5d.png)
临时解决

**Comment by EVA09** [comment]
嗯能解决就好，，也可以选择回滚到1.0.1版本  后面的版本的确是有问题。我现在已经完全忘记laravel了。。
