### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel-admin-extensions/cropper#2]
Hi, congratulations for this package!

What about move localization in resources/lang?

**Comment by EVA09** [comment]
sorry，my english is poor。 if you like this。 you can coding

**Comment by alberto-bottarini** [comment]
I'm not talking about translation, but to create external file in order to allow developers to translate texts

**Comment by z-song** [comment]
@alberto-bottarini Please feel free to send a pull request :D

**Comment by EVA09** [comment]
> I'm not talking about translation, but to create external file in order to allow developers to translate texts

The current version supports localization
