### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by cjlblog** [laravel-admin-extensions/cropper#22]
在laravel6.*的版本中不能用了

**Comment by EVA09** [comment]
糟糕啊。。。。那估计我只能把这个插件下线了。。。因为现在我已经无力去维护这个插件了。。。

发送自 Windows 10 版邮件应用

发件人: IT小书童
发送时间: 2020年1月8日 15:48
收件人: laravel-admin-extensions/cropper
抄送: Subscribed
主题: [laravel-admin-extensions/cropper] 功能失效 (#22)

在laravel6.*的版本中不能用了

**Comment by wongvio** [comment]
裁剪后保存失效
