### ISSUE TITLE
老哥 $form->cropper('avatar', __('Avatar'))->cRatio(100, 500) 这个无效呀

### ISSUE THREAD

**Issue by yanglei9999** [laravel-admin-extensions/cropper#30]
$form->cropper('avatar', __('Avatar'))->cRatio(100, 500) 
和 
$form->cropper('avatar', __('Avatar'))
一样没有区别
强制尺寸没有效果是什么原因, 已经是 1.0.4 版本

**Comment by yanglei9999** [comment]
我看了一下代码  /resources/views/cropper.blade.php

<div class="{{$viewClass['form-group']}} {!! !$errors->has($errorKey) ? '' : 'has-error' !!}">
    <label for="{{$id}}" class="{{$viewClass['label']}} control-label">{{$label}}</label>
    <div class="{{$viewClass['field']}}">

        @include('admin::form.error')
        <div class="btn btn-info pull-left cropper-btn">{{ trans('admin_cropper.choose') }}</div>
        @include('admin::form.help-block')
        <input class="cropper-file" type="file" accept="image/*"/>
        
        <img class="cropper-img" {!! empty($value) ? '' : 'src="'.$preview.'"'  !!}>
        <input class="cropper-input" name="{{$name}}" value="{{ old($column, $value) }}" {!! $attributes !!} />
        
    </div>
</div>

修改后就好使了:

<div class="{{$viewClass['form-group']}} {!! !$errors->has($errorKey) ? '' : 'has-error' !!}">
    <label for="{{$id}}" class="{{$viewClass['label']}} control-label">{{$label}}</label>
    <div class="{{$viewClass['field']}}">

        @include('admin::form.error')
        <div class="btn btn-info pull-left cropper-btn">{{ trans('admin_cropper.choose') }}</div>
        @include('admin::form.help-block')
        <input class="cropper-file" type="file" accept="image/*" {!! $attributes !!}/>
        
        <img class="cropper-img" {!! empty($value) ? '' : 'src="'.$preview.'"'  !!} {!! $attributes !!}>
        <input class="cropper-input" name="{{$name}}" value="{{ old($column, $value) }}" {!! $attributes !!} />

    </div>
</div>

看 {!! $attributes !!} 部分

老哥别马虎呀

**Comment by EVA09** [comment]
哈哈 中途大改了一次底层的实现逻辑，因为我最近都没直接用这个做项目，测试的很少，全靠你们这些大兄弟了。 你可以提个RP 或者你稍等我改下也可以

**Comment by yanglei9999** [comment]
我是小白, 还不会 RP , 等老哥修改

**Comment by EVA09** [comment]
大兄弟 试试得劲了不？ 哈哈。有啥子问题随时反馈。

**Comment by EVA09** [comment]
记得重新发布资源
php artisan vendor:publish --provider='Encore\Cropper\CropperServiceProvider' --force
