### ISSUE TITLE
在hasmany的时候使用有问题

### ISSUE THREAD

**Issue by sohenk** [laravel-admin-extensions/cropper#4]
我在hasmany时使用，只出现第一个，然后之后的第二、第三个都使用不了

**Comment by EVA09** [comment]
不 crop是个独立的组件（每个图片都需要独立的剪裁尺寸和独立的id来激活弹窗），并没有hasmany方法。
需要上传多个的时候 需要这样。
$form->cropper('content','label');
$form->cropper('content','label');
$form->cropper('content','label');

**Comment by EVA09** [comment]
我甚至都不知道 你是怎么在hasmany里面触发crop的 按理来说根本无法触发才对

**Comment by tanjhysj0** [comment]
> 我在hasmany时使用，只出现第一个，然后之后的第二，第三个都使用不了

我的也是，顺题解决了吗？

**Comment by EVA09** [comment]
问题解决啦！！！！！
