### ISSUE TITLE
can i use it in regular file, not in grid ?

### ISSUE THREAD

**Issue by GurgenYeranosyan** [laravel-admin-extensions/cropper#44]
if it is possible to use it in normal forms, for example with the media-manager package

**Comment by EVA09** [comment]
If you just need to use Cropper alone, you can go directly to Cropper.js

**Comment by GurgenYeranosyan** [comment]
thanks for the answer), but I would like to know exactly this plugin can be used media-manager?

**Comment by EVA09** [comment]
Cropper.js is a simple package. I think you can easily access it

**Comment by EVA09** [comment]
https://fengyuanchen.github.io/cropperjs/

this is Cropper.js url

**Comment by GurgenYeranosyan** [comment]
I tried it but when selecting always, the crop tool is always square how can I fix this?

**Comment by EVA09** [comment]
` 
  var cropper = new Cropper(image, {
                aspectRatio: 16 / 9,
                viewMode: 2,
            });
`
just  change  "aspectRatio"
you can reading  cropper doc

**Comment by GurgenYeranosyan** [comment]
thanks i figured out how it is sdekat , thank you for your help

**Comment by GurgenYeranosyan** [comment]
Cropper.js works but I need to know if I can use this particular opcode with Media manager https://laravel-admin.org/docs/en/extension-media-manager

**Comment by EVA09** [comment]
If you need to use it inside Media Manager, I think you need to rewrite the Media Manager plugin

**Comment by EVA09** [comment]
It's hard work, but you can see how the laravel-admin code works through the process
