### ISSUE TITLE
如何限制上传大小，限制上传最小宽高，隐藏原图按钮。

### ISSUE THREAD

**Issue by killjin** [laravel-admin-extensions/cropper#8]
如何限制上传大小，限制上传最小宽高，隐藏原图按钮。

**Comment by EVA09** [comment]
cRatio()方法可以限制剪裁宽高（但是不是强制的）。 限制上传大小请参看laravel-admin的手册 文件上传部分， 没记错的话这里是调用了laravel本身的验证器的 文件大小验证  方法应该是 size()
