### ISSUE TITLE
提示必须是图片

### ISSUE THREAD

**Issue by silasyao** [laravel-admin-extensions/cropper#9]
我有一个字段名称叫image，存储的是图片路径。使用这个cropper插件，裁切都没问题。但是保存的时候，提示“必须是图片”，没弄明白，咱这个插件不是基于imagefield和file的么？
我看了下，在chrome中，是以data的形式存储的，

能否给个示例，谢谢

**Comment by EVA09** [comment]
基础使用方法 $form->cropper('content','label')->cRatio($width,$height);
原理已经在readme.md 里面说明了。请换个字段先保证功能正常。不排除是你触发了底层的某个字段保护机制

**Comment by silasyao** [comment]
我找到问题了，通过composer require laravel-admin-ext/cropper加载到vendor目录中的Crop.php文件与github上该文件有所有不同，初步怀疑composer镜像问题，我用的是laravel-china的镜像。

**Comment by php-anson** [comment]
@silasyao 
修改下版本号：
```
composer require laravel-admin-ext/cropper:dev-master
```
